# Case Study - Data Analysis Airline
Analyst: Mochammad Daffa Putra Karyudi

## Preparation

In [1]:
import os
import dill
import py7zr
import pickle
import logging
import warnings
import numpy as np
import pandas as pd
import plotly.express as px
from datetime import datetime
import plotly.graph_objects as go
from plotly.subplots import make_subplots

warnings.filterwarnings('ignore')

dirloc = os.getcwd()

In [2]:
# Load data
df = pd.read_csv(f'{dirloc}/bahan_test.csv')

print("=== COMPREHENSIVE DATA CLEANING REPORT ===")
print(f"Analysis Date: 2025-06-11 04:55:51 UTC")
print(f"Analyst: Mochammad Daffa Putra Karyudi")
print(f"Dataset shape: {df.shape}")
display(df.head())

=== COMPREHENSIVE DATA CLEANING REPORT ===
Analysis Date: 2025-06-11 04:55:51 UTC
Analyst: Mochammad Daffa Putra Karyudi
Dataset shape: (3648142, 13)

,order_type,pax_name,order_id,generation_date,travel_date,status,agent,region,agent_type,airline,harga,class,sector
0,Domestic,f1473af8,PNR1,20181009,20181011,To Deliver,5770,DKI Jakarta,agent,XG,0.001324,X,CGK-PDG
1,Domestic,58475d2a,PNR2,20181009,20181010,To Deliver,5770,DKI Jakarta,agent,XG,0.001856,X,PKU-CGK
2,Domestic,000f89da,PNR3,20181009,20181027,To Deliver,5770,DKI Jakarta,agent,LE,0.002189,Q,LOP-CGK
3,Domestic,b78d5043,PNR4,20181009,20181010,To Deliver,5770,DKI Jakarta,agent,MI,0.001609,V,CGK-KNO
4,Domestic,bbaa07cd,PNR5,20181009,20190103,To Deliver,5770,DKI Jakarta,agent,AZ,0.001340,L,CGK-PGK

## Data Wrangling

In [3]:
# 1. Missing Values Check
print("\n1. MISSING VALUES ANALYSIS:")
missing_summary = df.isnull().sum()
missing_percentage = (missing_summary / len(df)) * 100
missing_report = pd.DataFrame({
    'Column': missing_summary.index,
    'Missing_Count': missing_summary.values,
    'Missing_Percentage': missing_percentage.values
})
display(missing_report)

1. MISSING VALUES ANALYSIS:

             Column  Missing_Count  Missing_Percentage
0        order_type              0            0.000000
1          pax_name              0            0.000000
2          order_id              0            0.000000
3   generation_date              0            0.000000
4       travel_date              0            0.000000
5            status              0            0.000000
6             agent              0            0.000000
7            region         205627            5.636486
8        agent_type              0            0.000000
9           airline              0            0.000000
10            harga              0            0.000000
11            class          62388            1.710131
12           sector              0            0.000000

In [4]:
# 2. Duplicate Analysis
print("\n2. DUPLICATE ANALYSIS:")
total_duplicates = df.duplicated().sum()
print(f"Total duplicate rows: {total_duplicates}")

2. DUPLICATE ANALYSIS:
Total duplicate rows: 39

### Data Cleaning

In [5]:
with open('clean_data.pkl', 'rb') as f:
    clean_function = dill.load(f)

# Define file paths
csv_path = os.path.join(dirloc, 'bahan_cleaned.csv')
archive_path = os.path.join(dirloc, 'bahan_cleaned.7z')

# 2. Check if the cleaned CSV already exists. If not, create it.
if not os.path.exists(csv_path):
    print(f"'{csv_path}' not found. Cleaning data and creating the CSV file...")
    
    # Run the cleaning function
    df_cleaned = clean_function(df, dirloc)
    
    # Save the cleaned dataframe to CSV
    df_cleaned.to_csv(csv_path, index=False)
    print(f"Successfully created '{csv_path}'.")
else:
    df_cleaned = pd.read_csv(csv_path)
    print(f"Skipping CSV creation: '{csv_path}' already exists.")


# 3. Check if the 7z archive already exists. If not, create it.
if not os.path.exists(archive_path):
    # Also check if the source CSV file exists before trying to archive it
    if os.path.exists(csv_path):
        print(f"'{archive_path}' not found. Archiving the CSV file...")
        
        # Create the 7z archive
        with py7zr.SevenZipFile(archive_path, 'w') as archive:
            archive.write(csv_path, os.path.basename(csv_path))
            
        print(f"Successfully created archive '{archive_path}'.")
    else:
        # This case would be unusual if the logic runs sequentially, but it's good practice
        print(f"Could not create archive because source file '{csv_path}' does not exist.")
else:
    print(f"Skipping archiving: '{archive_path}' already exists.")

2025-06-11 18:31:36,791 - INFO - INITIATING COMPREHENSIVE AIRLINE DATA CLEANING PIPELINE
2025-06-11 18:31:36,792 - INFO - Execution timestamp: 2025-06-11 11:31:36 UTC
2025-06-11 18:31:36,792 - INFO - Executed by: Mochammad Daffa Putra Karyudi
2025-06-11 18:31:36,792 - INFO - Initial dataset dimensions: 3,648,142 rows × 13 columns

'/home/keycode/Coding/github/Case-Study-Assignment/bahan_cleaned.csv' not found. Cleaning data and creating the CSV file...

2025-06-11 18:31:37,073 - INFO - Phase 1: Standardizing invalid region values to NULL
2025-06-11 18:31:38,349 - INFO - Invalid region values identified:
2025-06-11 18:31:38,350 - INFO -   Value '-1': 53,038 occurrences
2025-06-11 18:31:38,350 - INFO -   Value 'Indonesia': 84 occurrences
2025-06-11 18:31:38,350 - INFO -   Value 'indonesia': 24 occurrences
2025-06-11 18:31:38,351 - INFO -   Value 'INDONESIA': 24 occurrences
2025-06-11 18:31:38,598 - INFO - Phase 1 Complete - 53,170 records standardized to NULL
2025-06-11 18:31:38,599 - INFO - Total NULL regions: 258,797
2025-06-11 18:31:38,599 - INFO - Phase 2: Implementing region data formatting standards
2025-06-11 18:31:38,933 - INFO - Unique non-null regions before standardization: 96
2025-06-11 18:31:44,178 - INFO - Basic string formatting applied successfully
2025-06-11 18:31:44,179 - INFO - Phase 3: Applying Indonesian region standardization mapping
2025-06-11 18:31:44,180 - INFO - Region mapping successfully loaded from: /home/keycode/Coding/github/Case-Study-Assignment/indonesian_region_mapping_v1.0.pkl
2025-06-11 18:31:44,180 - INFO - Mapping entries: 151
2025-06-11 18:31:44,180 - INFO - Mapping version: 1.0
2025-06-11 18:31:44,181 - INFO - Created by: Mochammad Daffa Putra Karyudi
2025-06-11 18:31:46,681 - INFO - Unique non-null regions after mapping: 36
2025-06-11 18:31:46,682 - INFO - Phase 4: Implementing missing region imputation strategy
2025-06-11 18:31:46,811 - INFO - Missing regions requiring imputation: 258,797
2025-06-11 18:31:50,624 - INFO - Agents with missing regions: 8889
2025-06-11 18:31:50,624 - INFO - Agents eligible for mapping-based imputation: 5506
2025-06-11 18:32:16,789 - INFO - Phase 4 Complete - Remaining missing regions: 0
2025-06-11 18:32:16,789 - INFO - Records assigned 'Unknown Region': 96,337
2025-06-11 18:32:16,790 - INFO - Phase 5: Implementing flight class data processing with strict deletion protocol
2025-06-11 18:32:16,790 - INFO - Flight class mapping loaded from: /home/keycode/Coding/github/Case-Study-Assignment/flight_class_mapping_v2.2.pkl
2025-06-11 18:32:16,790 - INFO - Mapping entries: 106
2025-06-11 18:32:16,791 - INFO - Deletion targets identified: 47
2025-06-11 18:32:16,791 - INFO - Mapping version: 2.2
2025-06-11 18:32:16,936 - INFO - Pre-processing flight class statistics:
2025-06-11 18:32:16,937 - INFO -   Missing classes: 62,388
2025-06-11 18:32:16,937 - INFO -   Unique classes: 150
2025-06-11 18:32:16,937 - INFO - Phase 5a: Executing strict deletion protocol for problematic class entries
2025-06-11 18:32:22,868 - INFO - Records scheduled for deletion: 14,179
2025-06-11 18:32:22,868 - INFO - Top deletion categories:
2025-06-11 18:32:22,868 - INFO -   'Promo': 8,391 records
2025-06-11 18:32:22,869 - INFO -   'Economy': 3,944 records
2025-06-11 18:32:22,869 - INFO -   'BCLP': 1,071 records
2025-06-11 18:32:22,870 - INFO -   'BCLN': 436 records
2025-06-11 18:32:22,870 - INFO -   'DEPOSIT': 101 records
2025-06-11 18:32:22,871 - INFO -   'PELUNASAN': 78 records
2025-06-11 18:32:22,871 - INFO -   '-': 24 records
2025-06-11 18:32:22,871 - INFO -   'BOOKING FEE': 22 records
2025-06-11 18:32:22,871 - INFO -   'FULL PAYMENT': 20 records
2025-06-11 18:32:22,872 - INFO -   'OY': 10 records
2025-06-11 18:32:24,470 - INFO - Deletion protocol complete - New dataset dimensions: (3633963, 13)
2025-06-11 18:32:24,471 - INFO - Phase 5b: Applying flight class standardization mapping
2025-06-11 18:32:26,342 - INFO - Flight class standardization mapping applied successfully
2025-06-11 18:32:26,427 - INFO - Phase 5c: Processing remaining missing flight classes
2025-06-11 18:32:26,427 - INFO - Missing classes after deletion/mapping: 62,388
2025-06-11 18:33:12,385 - INFO - Class imputation complete - Remaining missing: 0
2025-06-11 18:33:12,493 - INFO - Post-processing flight class statistics:
2025-06-11 18:33:12,595 - INFO -   Missing classes: 0
2025-06-11 18:33:12,595 - INFO -   Unique classes: 26
2025-06-11 18:33:12,595 - INFO -   Class consolidation: 124 unique values
2025-06-11 18:33:12,596 - INFO - Phase 6: Executing duplicate record elimination
2025-06-11 18:33:22,072 - INFO - Duplicate records eliminated: 39
2025-06-11 18:33:22,073 - INFO - Phase 7: Conducting data integrity validation
2025-06-11 18:33:22,319 - INFO - Data integrity validation results:
2025-06-11 18:33:22,320 - INFO -   negative_lead_time_records: 1,191
2025-06-11 18:33:22,320 - INFO -   negative_price_records: 0
2025-06-11 18:33:22,320 - INFO -   excessive_lead_time_records: 9
2025-06-11 18:33:22,320 - INFO -   zero_price_records: 2
2025-06-11 18:33:22,765 - INFO - COMPREHENSIVE DATA CLEANING PIPELINE COMPLETED SUCCESSFULLY
2025-06-11 18:33:22,765 - INFO - Initial dataset dimensions: (3648142, 13)
2025-06-11 18:33:22,765 - INFO - Final dataset dimensions: (3633924, 13)
2025-06-11 18:33:22,766 - INFO - Data retention rate: 99.61%
2025-06-11 18:33:22,766 - INFO - Total records eliminated: 14,218
2025-06-11 18:33:22,766 - INFO - FINAL DATA DISTRIBUTION ANALYSIS:
2025-06-11 18:33:22,767 - INFO - Top 10 regional distributions:
2025-06-11 18:33:22,901 - INFO -   DKI Jakarta: 1,722,103
2025-06-11 18:33:22,902 - INFO -   Jawa Barat: 282,461
2025-06-11 18:33:22,903 - INFO -   Sumatera Utara: 192,034
2025-06-11 18:33:22,903 - INFO -   Kalimantan Timur: 144,070
2025-06-11 18:33:22,903 - INFO -   Jawa Timur: 103,891
2025-06-11 18:33:22,903 - INFO -   Riau: 102,311
2025-06-11 18:33:22,904 - INFO -   Unknown Region: 96,008
2025-06-11 18:33:22,904 - INFO -   Banten: 95,138
2025-06-11 18:33:22,904 - INFO -   Bali: 94,713
2025-06-11 18:33:22,905 - INFO -   Sumatera Selatan: 88,728
2025-06-11 18:33:22,905 - INFO - Top 10 flight class distributions:
2025-06-11 18:33:23,006 - INFO -   V: 370,266
2025-06-11 18:33:23,007 - INFO -   X: 323,465
2025-06-11 18:33:23,008 - INFO -   Q: 314,891
2025-06-11 18:33:23,008 - INFO -   T: 267,718
2025-06-11 18:33:23,009 - INFO -   N: 255,883
2025-06-11 18:33:23,009 - INFO -   L: 244,257
2025-06-11 18:33:23,010 - INFO -   M: 228,360
2025-06-11 18:33:23,010 - INFO -   Y: 206,642
2025-06-11 18:33:23,010 - INFO -   K: 183,550
2025-06-11 18:33:23,011 - INFO -   H: 173,294

Successfully created '/home/keycode/Coding/github/Case-Study-Assignment/bahan_cleaned.csv'.
'/home/keycode/Coding/github/Case-Study-Assignment/bahan_cleaned.7z' not found. Archiving the CSV file...
Successfully created archive '/home/keycode/Coding/github/Case-Study-Assignment/bahan_cleaned.7z'.

### Data Validation

In [6]:
# 4. Business Logic Validation
print("\n4. BUSINESS LOGIC VALIDATION:")
df_clean = df_cleaned.copy()

# Convert dates with error handling
df_clean['generation_date'] = pd.to_datetime(df_clean['generation_date'], format='%Y%m%d', errors='coerce')
df_clean['travel_date'] = pd.to_datetime(df_clean['travel_date'], format='%Y%m%d', errors='coerce')

# Check date conversion success
date_conversion_issues = {
    'generation_date_invalid': df_clean['generation_date'].isnull().sum(),
    'travel_date_invalid': df_clean['travel_date'].isnull().sum()
}
print(f"Date conversion issues: {date_conversion_issues}")

df_clean['lead_time'] = (df_clean['travel_date'] - df_clean['generation_date']).dt.days

# Check for logical inconsistencies
logic_issues = {
    'negative_lead_time': (df_clean['lead_time'] < 0).sum(),
    'negative_prices': (df_clean['harga'] < 0).sum(),
    'extreme_lead_time': (df_clean['lead_time'] > 365).sum(),
    'zero_prices': (df_clean['harga'] == 0).sum()
}
print(f"Logic issues found: {logic_issues}")

4. BUSINESS LOGIC VALIDATION:
Date conversion issues: {'generation_date_invalid': 0, 'travel_date_invalid': 0}
Logic issues found: {'negative_lead_time': 1191, 'negative_prices': 0, 'extreme_lead_time': 9, 'zero_prices': 2}

In [7]:
# 5. Text Data Standardization
print("\n5. TEXT DATA STANDARDIZATION:")

# Check for potential inconsistencies in categorical data
categorical_analysis = {}
for col in ['order_type', 'status', 'agent_type', 'airline', 'class', 'region']:
    unique_values = df_clean[col].unique()
    categorical_analysis[col] = {
        'unique_count': len(unique_values),
        'values': list(unique_values)
    }
    print(f"{col}: {len(unique_values)} unique values")

5. TEXT DATA STANDARDIZATION:
order_type: 2 unique values
status: 3 unique values
agent_type: 5 unique values
airline: 162 unique values
class: 26 unique values
region: 37 unique values

In [8]:
# 6. Outlier Detection
print("\n6. OUTLIER DETECTION:")
price_stats = df_clean['harga'].describe()
Q1 = df_clean['harga'].quantile(0.25)
Q3 = df_clean['harga'].quantile(0.75)
IQR = Q3 - Q1
outlier_bounds = {
    'lower_bound': Q1 - 1.5 * IQR,
    'upper_bound': Q3 + 1.5 * IQR
}
outliers = ((df_clean['harga'] < outlier_bounds['lower_bound']) | 
            (df_clean['harga'] > outlier_bounds['upper_bound'])).sum()
print(f"Price outliers detected: {outliers}")
print(f"Outlier bounds: {outlier_bounds}")

6. OUTLIER DETECTION:
Price outliers detected: 230854
Outlier bounds: {'lower_bound': 0.0001048852543764499, 'upper_bound': 0.00305932954337925}

In [9]:
# 7. Data Quality Score
print("\n7. DATA QUALITY SCORE:")
total_records = len(df_clean)
missing_summary = df_clean.isnull().sum()
total_duplicates = df_clean.duplicated().sum()
logic_issues = {
    'negative_lead_time': (df_clean['lead_time'] < 0).sum(),
    'negative_prices': (df_clean['harga'] < 0).sum(),
    'extreme_lead_time': (df_clean['lead_time'] > 365).sum(),
    'zero_prices': (df_clean['harga'] == 0).sum()
}
quality_metrics = {
    'completeness': (1 - missing_summary.sum() / (total_records * len(df_clean.columns))) * 100,
    'uniqueness': (1 - total_duplicates / total_records) * 100,
    'validity': (1 - sum(logic_issues.values()) / total_records) * 100,
    'consistency': 95  # Based on categorical data review
}
overall_quality = np.mean(list(quality_metrics.values()))
print(f"Data Quality Metrics: {quality_metrics}")
print(f"Overall Data Quality Score: {overall_quality:.2f}%")

print(f"\nCleaned dataset ready for analysis: {df_clean.shape}")

7. DATA QUALITY SCORE:
Data Quality Metrics: {'completeness': 100.0, 'uniqueness': 100.0, 'validity': 99.96692280851222, 'consistency': 95}
Overall Data Quality Score: 98.74%

Cleaned dataset ready for analysis: (3633924, 14)

## Exploratory Data Analysis

In [10]:
# Question 1: Distribution of orders by airline (Top 10)
print("Q1: What are top 10 distribution of orders by airline?")
airline_dist = df_cleaned['airline'].value_counts().head(10).reset_index()
airline_dist.columns = ['airline', 'order_count']
fig1 = px.pie(airline_dist, values='order_count', names='airline', 
              title="Q1: Order Distribution by Airline (Top 10)")
fig1.show()

Q1: What are top 10 distribution of orders by airline?

In [11]:
# Question 2: Average ticket prices by airline (Top 10)
print("Q2: Top 10 average ticket prices by airline")
avg_price_airline = df_cleaned.groupby('airline')['harga'].mean().reset_index()

# Sort by average price from highest to lowest and get top 10
avg_price_airline = avg_price_airline.sort_values('harga', ascending=False).head(10)

# Create horizontal bar chart
fig2 = px.bar(avg_price_airline, x='harga', y='airline',
              title="Q2: Average Ticket Prices by Airline (Top 10)",
              orientation='h')  # 'h' for horizontal

# Update layout to improve readability
fig2.update_layout(
    yaxis={'categoryorder': 'total ascending'},  # This ensures the sorting is maintained
    xaxis_title="Average Price (Harga)",
    yaxis_title="Airline",
    width=1000,  # Increase width
    height=600   # Reduced height since we only have 10 bars now
)

fig2.show()

Q2: Top 10 average ticket prices by airline

In [12]:
# Question 3: Regional booking analysis
print("Q3: Which regions generate the most bookings?")
region_bookings = df_cleaned['region'].value_counts().reset_index()
region_bookings.columns = ['region', 'bookings']

# Sort by bookings from highest to lowest
region_bookings = region_bookings.sort_values('bookings', ascending=False)

fig3 = px.bar(region_bookings, x='region', y='bookings',
              title="Q3: Bookings by Region")

# Correct way to update x-axis properties
fig3.update_layout(xaxis_tickangle=45)
fig3.show()

Q3: Which regions generate the most bookings?

In [13]:
# Question 4: Booking patterns over travel dates
print("Q4: What are the booking patterns over travel dates?")
travel_date_pattern = df_cleaned.groupby('travel_date').size().reset_index(name='bookings')
fig4 = px.line(travel_date_pattern, x='travel_date', y='bookings',
               title="Q4: Booking Patterns Over Travel Dates")
fig4.show()

Q4: What are the booking patterns over travel dates?

In [14]:
# Question 5: Generation date booking trends
print("Q5: What is the booking trend over generation dates?")
generation_trend = df_cleaned.groupby('generation_date').size().reset_index(name='bookings')
fig5 = px.line(generation_trend, x='generation_date', y='bookings',
                title="Q5: Daily Booking Generation Trend")
fig5.show()

Q5: What is the booking trend over generation dates?

In [15]:
# Question 6: Flight class popularity
print("Q6: Which flight classes are most popular?")
class_popularity = df_cleaned['class'].value_counts().reset_index()
class_popularity.columns = ['flight_class', 'count']
fig6 = px.bar(class_popularity, x='flight_class', y='count',
              title="Q6: Flight Class Popularity")
fig6.show()

Q6: Which flight classes are most popular?

In [16]:
# Question 7: Top flight sectors
print("Q7: What are the top 10 most popular flight sectors?")
top_sectors = df_cleaned['sector'].value_counts().head(10).reset_index()
top_sectors.columns = ['sector', 'frequency']
fig7 = px.bar(top_sectors, x='sector', y='frequency',
              title="Q7: Top 10 Flight Sectors")
fig7.show()

Q7: What are the top 10 most popular flight sectors?

In [17]:
# Question 8: Revenue distribution by airline
print("Q8: Whate are Top 10 revenue distribution by airline?")
revenue_by_airline = df_cleaned.groupby('airline')['harga'].sum().reset_index()
# Sort by average price from highest to lowest and get top 10
revenue_by_airline = revenue_by_airline.sort_values('harga', ascending=False).head(10)

fig8 = px.pie(revenue_by_airline, values='harga', names='airline',
               title="Q8: Revenue Distribution by Airline")
fig8.show()

Q8: Whate are Top 10 revenue distribution by airline?

In [18]:
# Question 9: Booking patterns by day of week
print("Q9: How do booking patterns differ by day of the week?")
df_clean_temp = df_cleaned.copy()
df_clean_temp['travel_weekday'] = df_clean_temp['travel_date'].dt.day_name()
weekday_bookings = df_clean_temp['travel_weekday'].value_counts().reset_index()
weekday_bookings.columns = ['weekday', 'bookings']
# Reorder by weekday
weekday_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekday_bookings['weekday'] = pd.Categorical(weekday_bookings['weekday'], 
                                           categories=weekday_order, ordered=True)
weekday_bookings = weekday_bookings.sort_values('weekday')
fig9 = px.bar(weekday_bookings, x='weekday', y='bookings',
               title="Q9: Bookings by Day of Week")
fig9.show()

Q9: How do booking patterns differ by day of the week?